### ISSUE TITLE
[meta] DevHub

### ISSUE THREAD

**Issue by moul** [scaleway/devhub#1]
Original PR: #71 

TODO: 

- [x] serve http content
- [x] communicate with scaleway API
  - [x] check default bootscript
  - [x] retrieve build date
- [x] parse image hub
  - [x] retrieve uuid date etc
- [x] communicate with docker registry
  - [x] retrieve tags/date etc
- [x] get github sources
  - [x] parse dockerfiles
    - [ ] compare FROM with other images
  - [ ] check commit date repo
  - [ ] check commit date image-tools
- [ ] retrieve corresponding jenkins builds
- [x] badge POC
- [ ] oembed POC
- [ ] GitHub search

(original issue: https://github.com/scaleway/image-tools/issues/105)
